### ISSUE TITLE
Useful Links Tab on Main Menu

### ISSUE THREAD

**Issue by Razielous** [usulrasolas/PCEternitiesMap#11]
There should be a tab on the Main Menu that has links to the rules of Planeschase,
and the Rules to Blind Eternities. 

Possibly also a similar menu option in-game.

**Comment by usulrasolas** [comment]
hey! didn't you commit this to phenom and I fixed it? If so replyandclose

**Comment by usulrasolas** [comment]
nevermind, I didn't read it properly... how do you want this? a tab with like rules references? That sounds like a whole enhancement in itself, a rule reference tab with any/all needed?

**Comment by Razielous** [comment]
Naw, just links

**Comment by usulrasolas** [comment]
I guess what I'm saying is with my help, you're in charge of making the menu full of links?
