### ISSUE TITLE
Potential Error on Spatial Merging

### ISSUE THREAD

**Issue by Razielous** [usulrasolas/PCEternitiesMap#14]
**Describe the bug**
Spatial Merging disappeared when one of the planes had counters on it.

**To Reproduce**
1. Have Spatial Merging Phenomenon Trigger
2. While still zoomed in, i put a counter on the left side plane
3. then i click on spatial merging to go back to the board
4. Spatial Merging disappeared, and it just displayed the back of the card, and when i traveled away it repopulated the square spatial merging was in.

**Expected behavior**
Spatial Merging should not have disappeared. i dont know if its because i put the counters on during the initial display/activation, or because i put counters on at all.

**Comment by Razielous** [comment]
On further inspection, if i don't put counters on during the initial zoom display, Spatial Merging doesn't disappear. But when i put counters on during "normal play" they are not persistant, and reset when zoom is disabled

**Comment by usulrasolas** [comment]
This should be fixed now! Thanks
