### ISSUE TITLE
Make the card images a separate download

### ISSUE THREAD

**Issue by allentiak** [usulrasolas/PCEternitiesMap#18]
Just to avoid any copyright infringement...

I guess those images are on Scryfall?

**Comment by usulrasolas** [comment]
Yes, these are publicly available and we claim no rights to them. They are
available on scryfall and a few other resources including other
planeschase format apps.

Wizards has also stated for the reuse of these resources, selling or
portraying them as our content is the issue. Credit given for game,
pictures, and other WotC content on launcher and in documentation.

I'm not looking to replace the physical cards, but enable them to be played
in a variant suggested by WotC that is not playable for those without huge
or secondary tables.
