### ISSUE TITLE
Phenomenon and Non-Phenomenon Sets

### ISSUE THREAD

**Issue by Razielous** [usulrasolas/PCEternitiesMap#32]
**Describe the bug**
enabling Phenomenon and sets that don't have phenomenon simultaneously result in a errored out game.

**To Reproduce**
1. enable phenomenon
2. enable any set without phenomenon
        - Amonkhet
        - Fiora
        - probably the other non-phenom Multiverse Sets
3. create new game

**Expected behavior**
a new game should start and any phenom triggers would be ignored, if possilbe

**Comment by usulrasolas** [comment]
Appears that the links between the chk.checked and the variable got cut somehow, will make patch and push with resolves tag

**Comment by usulrasolas** [comment]
This appears to be fixed, was missing handler on checkedchanged on affected issues
