### ISSUE TITLE
Various Feature Suggestions

### ISSUE THREAD

**Issue by Razielous** [usulrasolas/PCEternitiesMap#5]
Counter on plane zoomed with plane for easier viewing.
~~Change label display array colors/size to account for color blindness.~~

*~~Mount Keralia~~
~~space between the number and the word Damage during trigger popup~~
~~-set option(s) for counter persistence~~
      --~~enable/disable counters reset when leaving plane~~
     --~~enable/disable counter reset when leaving game board~~
      --~~enable/disable counter reset when returns to deck~~

*~~Aerotopolis~~
~~when 10 counters trigger the popup, also zoom in on the plane~~
-~~option for plane to have more than 10 counters~~
            ~~reword pop up to say "10 or more counters~~
~~-set option(s) for counter persistence~~
      --~~enable/disable counters reset when leaving plane~~
     --~~enable/disable counter reset when leaving game board~~
      --~~enable/disable counter reset when returns to deck~~

*~~Pools of Becoming~~
Have the popup choose between ending the chaos trigger or ~~displaying the oracle text/rulings for pools of  becoming.~~

**Comment by usulrasolas** [comment]
all complete in rc3
