### ISSUE TITLE
Incorporation of the new planes coming out with March of the Machines - Commander

### ISSUE THREAD

**Issue by Hector-Xavier** [usulrasolas/PCEternitiesMap#61]
If this app is still being supported, will you be adding the new planes? I had been searching for such a utility for some time and I am glad that the way you have structured it allows this many options for customization, I would really like us to keep using it in our future games.

**Comment by Razielous** [comment]
Yes, we are currently in the works to add the new planes from the March of the Machine Commander decks, it should be coming very soon!
